collections:
  - name: community.libvirt
    source: https://192.168.50.202/api/galaxy/content/rh-certified/

  - name: community.general
    source: https://192.168.50.202/api/galaxy/content/rh-certified/
    
